# site settings
title: zzmp.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zzmp.github.io" # the base hostname & protocol for your site
description: >
  Another software engineer's blog.<br>
  Usually just my tinkerings.

# personal settings
my:
    name: Zach Pomerantz
    email: zmp@umich.edu
    github_username:  zzmp
    linkedin_username: zpomerantz

# build settings
markdown: kramdown
